# Change these first
owner: treant-io # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: PROD-Zeus
    url: https://api-prod.treant.io/health/zeus
  - name: PROD-Ares
    url: https://api-prod.treant.io/health/ares
  - name: PROD-Consus
    url: https://api-prod.treant.io/health/consus
  - name: PROD-Aquiles
    url: https://app.treant.io
  - name: Stagging-Zeus
    url: https://apim.treant.io/health/zeus
  - name: Stagging-Ares
    url: https://apim.treant.io/health/ares
  - name: Stagging-Consus
    url: https://apim.treant.io/health/consus
  - name: Stagging-Aquiles
    url: https://aquiles-staging.treant.io
  - name: Time-Tecro-UI
    url: https://test-7b58.gentlesmoke-775a1338.eastus.azurecontainerapps.io/ 
    
assignees:
  - damianpuente
  - Eber-io
  - l-canales
  
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
